CREATE TABLE IF NOT EXISTS sales(
    id SERIAL PRIMARY KEY,
    name TEXT,
    main_category TEXT,
    sub_category TEXT,
    image TEXT,
    link TEXT,
    ratings REAL,
    no_of_ratings REAL,
    discount_price REAL,
    actual_price REAL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS marketing(
    id SERIAL PRIMARY KEY,
    product_id TEXT,
    prices_amount_max REAL,
    prices_amount_min REAL,
    prices_availability TEXT,
    prices_condition TEXT,
    prices_currency TEXT,
    prices_date_seen TEXT,
    prices_is_sale BOOLEAN,
    prices_merchant TEXT,
    prices_shipping REAL,
    prices_source_urls TEXT,
    asins TEXT,
    brand TEXT,
    categories TEXT,
    date_added TIMESTAMP,
    date_updated TIMESTAMP,
    image_urls TEXT,
    KEYS TEXT,
    manufacturer TEXT,
    manufacturer_number TEXT,
    name TEXT,
    primary_categories TEXT,
    source_urls TEXT,
    upc TEXT,
    weight_in_pounds REAL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS scraping(
    id SERIAL PRIMARY KEY,
    judul TEXT,
    topik TEXT,
    sub_topik TEXT,
    topik_pilihan TEXT,
    tanggal_waktu_publish TIMESTAMP,
    redaksi TEXT,
    advetorial TEXT,
    isi_berita TEXT,
    link TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);